### ISSUE TITLE
dragula-model events

### ISSUE THREAD

**Issue by panzershreck** [bevacqua/angular-dragula#30]
When I add options with dragulaService.options, bag was added, then in link fuction models just added to drake.models, without handleModels, so model's events doesn't work.

**Comment by gligoran** [comment]
+1

**Comment by DanielSchuech** [comment]
I ve found this out a month ago but missed it to post.

For the moment try to install the follwing commit: 03b99ad7769b6731db2f005481d06901ba5b70da

```javascript
npm install git+https://github.com/bevacqua/angular-dragula.git#03b99ad7769b6731db2f005481d06901ba5b70da
```

It´s caused by the next commit after mine. Thats a bug which needs to be fixed.
@luckylooke I could have a look into it and try to fix it if you want. As I remeber the problem is not trivial.

**Comment by gligoran** [comment]
@DanielSchuech: I commented [here](https://github.com/bevacqua/angular-dragula/pull/17#issuecomment-144358524) how I fixed this for myself. This works for my use case, but it might cause other problems I'm not aware of.

**Comment by DanielSchuech** [comment]
That´s a quickfix but no solutions I would say. If you doesn´t use setOptions you can use the dragula-model directive and otherwise you need to use the exposed handleModels function. This usage isn´t intuitiv for unexperienced users.

I would undo the canges of joncys commit and would handle the models everytime. The check if an model exists would I do at first in the removeModel and dropModel function. That´s my best idea for the moment.

**Comment by luckylooke** [comment]
@DanielSchuech you have green for solving this issue, I wanted to solve it also with #16 at once, but I am too busy these weeks. If you can handle at least this issue, it would be great. I will take care of rest in few weeks I hope ;)
